# ========================================
# KAFKA REACTIVE MESSAGING
# ========================================

# Canal de salida (outgoing-order-events)
mp.messaging.outgoing.outgoing-order-events.connector=smallrye-kafka
mp.messaging.outgoing.outgoing-order-events.topic=order-events
mp.messaging.outgoing.outgoing-order-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.outgoing-order-events.value.serializer=com.infinity.poc.infrastructure.serialization.OrderEventSerializer
mp.messaging.outgoing.outgoing-order-events.max.block.ms=3000

# ========================================
# DEV SERVICES (Podman como container runtime)
# ========================================
quarkus.kafka.devservices.enabled=true
quarkus.kafka.devservices.topic-partitions.order-events=1
quarkus.kafka.devservices.provider=strimzi

# Token esperado para validación simple
app.security.api-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

# Swagger / OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.infinity.poc".level=DEBUG
