# ========================================
# KAFKA REACTIVE MESSAGING
# ========================================

# Canal de salida (outgoing-order-events)
mp.messaging.outgoing.outgoing-order-events.connector=smallrye-kafka
mp.messaging.outgoing.outgoing-order-events.topic=order-events
mp.messaging.outgoing.outgoing-order-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.outgoing-order-events.value.serializer=com.infinity.poc.infrastructure.serialization.OrderEventSerializer
mp.messaging.outgoing.outgoing-order-events.max.block.ms=3000

# ========================================
# DEV SERVICES (Podman como container runtime)
# ========================================
%dev.quarkus.kafka.devservices.enabled=true
%dev.quarkus.kafka.devservices.topic-partitions.order-events=1
%dev.quarkus.kafka.devservices.provider=strimzi

# ========================================
# PRODUCCION / COMPOSE
# ========================================
%prod.quarkus.kafka.devservices.enabled=false
%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Token esperado para validación simple
app.security.api-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

# Swagger / OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# ========================================
# METRICAS - Micrometer / Prometheus
# ========================================
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.infinity.poc".level=DEBUG
